# Generated by Django 5.1.6 on 2025-11-17 18:40

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(blank=True, unique=True, verbose_name='Número de radicado')),
            ],
            options={
                'verbose_name': 'Número de Radicado',
                'verbose_name_plural': 'Números de Radicados',
                'db_table': 'FILE_NUMBER',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CauseRejectPqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('description', models.TextField(max_length=600, null=True, verbose_name='Descripción')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actualización')),
            ],
            options={
                'verbose_name': 'Causal para rechazar una PQR',
                'verbose_name_plural': 'Causales para rechazar PQRs',
                'db_table': 'CAUSE_REJECT_PQR',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralTypeDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actualización')),
            ],
            options={
                'verbose_name': 'Tipo de daño externo',
                'verbose_name_plural': 'Tipos de daños externos',
                'db_table': 'TYPE_DAMAGE_GENERAL',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('fk_group', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actualización')),
            ],
            options={
                'verbose_name': 'Origen PQR',
                'verbose_name_plural': 'Origenes de PQRs',
                'db_table': 'ORIGIN_PQR',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPqrClosed',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('file_number', models.PositiveBigIntegerField(blank=True, db_index=True, verbose_name='Número de radicado')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, default=1, verbose_name='Estado')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('dni', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='No es un número de documento válido', regex='^\\d{7,10}$')], verbose_name='Cédula ciudadania')),
                ('phone_number', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='No es un número de teléfono válido', regex='^(3|6)\\d{9}$')], verbose_name='Número teléfono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('observation', models.TextField(max_length=600, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk_node_reported', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.node', verbose_name='Nodo reportado')),
                ('fk_type_damage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.generaltypedamage', verbose_name='Tipo de daño')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fk_origin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.origin', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'historical PQR cerrada',
                'verbose_name_plural': 'historical PQRs cerradas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPqrActive',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('file_number', models.PositiveBigIntegerField(blank=True, db_index=True, verbose_name='Número de radicado')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, default=1, verbose_name='Estado')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('dni', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='No es un número de documento válido', regex='^\\d{7,10}$')], verbose_name='Cédula ciudadania')),
                ('phone_number', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='No es un número de teléfono válido', regex='^(3|6)\\d{9}$')], verbose_name='Número teléfono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('observation', models.TextField(max_length=600, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk_node_reported', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.node', verbose_name='Nodo reportado')),
                ('fk_type_damage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.generaltypedamage', verbose_name='Tipo de daño')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fk_origin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pqrs.origin', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'historical PQR activa',
                'verbose_name_plural': 'historical PQRs activas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PqrActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file_number', models.PositiveBigIntegerField(blank=True, db_index=True, unique=True, verbose_name='Número de radicado')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, default=1, verbose_name='Estado')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('dni', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='No es un número de documento válido', regex='^\\d{7,10}$')], verbose_name='Cédula ciudadania')),
                ('phone_number', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='No es un número de teléfono válido', regex='^(3|6)\\d{9}$')], verbose_name='Número teléfono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('observation', models.TextField(max_length=600, verbose_name='Observaciones')),
                ('fk_node_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.node', verbose_name='Nodo reportado')),
                ('fk_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pqrs.origin', verbose_name='Origen')),
                ('fk_type_damage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqrs.generaltypedamage', verbose_name='Tipo de daño')),
            ],
            options={
                'verbose_name': 'PQR activa',
                'verbose_name_plural': 'PQRs activas',
                'db_table': 'PQR_ACTIVE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PqrActiveRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha entrada')),
                ('output_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha salida')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, verbose_name='Estado')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pqrs.causerejectpqr', verbose_name='Causal')),
                ('fk_pqr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqrs.pqractive', verbose_name='PQR')),
            ],
            options={
                'verbose_name': 'Ruta PQR activa',
                'verbose_name_plural': 'Ruta PQRs activas',
                'db_table': 'PQR_ACTIVE_ROUTE',
                'ordering': ['fk_pqr'],
            },
        ),
        migrations.CreateModel(
            name='PqrClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file_number', models.PositiveBigIntegerField(blank=True, db_index=True, unique=True, verbose_name='Número de radicado')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, default=1, verbose_name='Estado')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='No es un nombre válido', regex='^[A-Za-zá-úüñÁ-ÚÜÑ\\s]+$')], verbose_name='Nombre')),
                ('dni', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='No es un número de documento válido', regex='^\\d{7,10}$')], verbose_name='Cédula ciudadania')),
                ('phone_number', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='No es un número de teléfono válido', regex='^(3|6)\\d{9}$')], verbose_name='Número teléfono')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('observation', models.TextField(max_length=600, verbose_name='Observaciones')),
                ('fk_node_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.node', verbose_name='Nodo reportado')),
                ('fk_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pqrs.origin', verbose_name='Origen')),
                ('fk_type_damage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqrs.generaltypedamage', verbose_name='Tipo de daño')),
            ],
            options={
                'verbose_name': 'PQR cerrada',
                'verbose_name_plural': 'PQRs cerradas',
                'db_table': 'PQR_CLOSED',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PqrClosedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha entrada')),
                ('output_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha salida')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Anulado'), (1, 'Recibido'), (2, 'En proceso'), (3, 'Atentida')], db_index=True, verbose_name='Estado')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pqrs.causerejectpqr', verbose_name='Causal')),
                ('fk_pqr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqrs.pqrclosed', verbose_name='PQR')),
            ],
            options={
                'verbose_name': 'Ruta PQR cerrada',
                'verbose_name_plural': 'Ruta PQRs cerradas',
                'db_table': 'PQR_CLOSED_ROUTE',
                'ordering': ['fk_pqr'],
            },
        ),
        migrations.AddIndex(
            model_name='pqractive',
            index=models.Index(fields=['status'], name='PQR_ACTIVE_status_9df965_idx'),
        ),
        migrations.AddIndex(
            model_name='pqractive',
            index=models.Index(fields=['file_number'], name='PQR_ACTIVE_file_nu_6d7cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='pqractive',
            index=models.Index(fields=['fk_node_reported', 'status'], name='PQR_ACTIVE_fk_node_fc0689_idx'),
        ),
        migrations.AddIndex(
            model_name='pqractiveroute',
            index=models.Index(fields=['fk_pqr'], name='PQR_ACTIVE__fk_pqr__049bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='pqractiveroute',
            index=models.Index(fields=['fk_pqr', 'state'], name='PQR_ACTIVE__fk_pqr__5d7aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrclosed',
            index=models.Index(fields=['status'], name='PQR_CLOSED_status_98f811_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrclosed',
            index=models.Index(fields=['file_number'], name='PQR_CLOSED_file_nu_4b222a_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrclosed',
            index=models.Index(fields=['fk_node_reported', 'status'], name='PQR_CLOSED_fk_node_d54d66_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrclosedroute',
            index=models.Index(fields=['fk_pqr'], name='PQR_CLOSED__fk_pqr__aa122a_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrclosedroute',
            index=models.Index(fields=['fk_pqr', 'state'], name='PQR_CLOSED__fk_pqr__4ff9df_idx'),
        ),
    ]
