# Generated by Django 5.1.6 on 2026-06-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('telemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalluminaire',
            name='fk_photocell_smart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='telemanagement.smartphotocell', verbose_name='Fotocelda inteligente'),
        ),
        migrations.AddField(
            model_name='luminaire',
            name='fk_photocell_smart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telemanagement.smartphotocell', verbose_name='Fotocelda inteligente'),
        ),
    ]
