# Generated by Django 5.1.6 on 2026-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('users', '0002_remove_historicaluser_avatar_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='comunas',
            field=models.ManyToManyField(blank=True, to='infrastructure.comuna', verbose_name='Comunas'),
        ),
    ]
