# Generated by Django 5.1.6 on 2025-11-13 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inicio de seción')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('connection', models.CharField(max_length=255, null=True, verbose_name='Información conexión')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial inicio sesión',
                'verbose_name_plural': 'Historial inicios de sesión',
                'db_table': 'LOGIN_HISTORY',
                'ordering': ['-id'],
            },
        ),
    ]
