# Generated by Django 5.1.6 on 2026-06-27 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhotocell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
                ('devui', models.CharField(max_length=16, unique=True, verbose_name='DevEUI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actualización')),
            ],
            options={
                'verbose_name': 'Fotocelda Inteligente',
                'verbose_name_plural': 'Fotoceldas Inteligentes',
                'db_table': 'SMART_PHOTOCELL',
                'ordering': ['id'],
            },
        ),
    ]
