# Generated by Django 5.1.6 on 2025-11-13 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Título')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Si no se selecciona ningún grupo, el menú será público', related_name='menu_groups', to='auth.group', verbose_name='Grupos permitidos')),
            ],
            options={
                'verbose_name': 'Grupo de Menú',
                'verbose_name_plural': 'Grupos de Menú',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url_name', models.CharField(help_text="Nombre del patrón de URL de Django (ej: 'infrastructure:list')", max_length=100, verbose_name='Nombre de URL')),
                ('icon', models.CharField(blank=True, help_text="Clase o nombre del icono (ej: 'layout-dashboard' para Lucide)", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('url_kwargs', models.JSONField(blank=True, default=dict, help_text='Parámetros para reverse()', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem', verbose_name='Menú Padre')),
            ],
            options={
                'verbose_name': 'Item de Menú',
                'verbose_name_plural': 'Items de Menú',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menugroup')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menuitem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu_group', 'menu_item')},
            },
        ),
        migrations.AddField(
            model_name='menugroup',
            name='items',
            field=models.ManyToManyField(related_name='menu_groups', through='menus.MenuGroupItem', to='menus.menuitem', verbose_name='Items del menú'),
        ),
    ]
